export const models = [
  {
    id: "text-embedding-ada-002",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-similarity-ada-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-similarity-babbage-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-similarity-curie-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-similarity-davinci-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-ada-doc-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-ada-query-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-babbage-doc-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-babbage-query-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-curie-doc-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-curie-query-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-davinci-doc-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "text-search-davinci-query-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "code-search-ada-code-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "code-search-ada-text-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "code-search-babbage-code-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  {
    id: "code-search-babbage-text-001",
    private: false,
    pipeline_tag: null,
    provider: "openai",
  },
  { id: "small", private: false, pipeline_tag: null, provider: "cohere" },
  { id: "large", private: false, pipeline_tag: null, provider: "cohere" },
];
